name: PHP Application Deployment

on:
  push:
    branches: [ "test" ]

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: centos:7
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        run: |
         sudo yum install -y php php-cli php-fpm php-mysqlnd php-zip php-devel php-gd php-mcrypt php-mbstring php-curl php-xml php-pear php-bcmath php-json

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          sudo chmod +x /usr/local/bin/composer

      - name: Install Composer dependencies
        run: |
          cd /var/www/html
          sudo composer install --no-dev --optimize-autoloader

      - name: Start PHP built-in server
        run: php -S sifydev.digitalrupay.com -t /var/www/html &

      - name: Wait for PHP built-in server to start
        run: sleep 5

      - name: Test PHP application
        run: curl http://sifydev.digitalrupay.com/Welcome
