name: PHP Application Deployment

on:
  push:
    branches: [ "test" ]

jobs:
  deploy:
    runs-on: self-hosted
    
        container:
          image: php:7.4-cli

      - name: Set up PHP
        uses: docker/metadata-action@v3
        with:
          image: 'php:7.4-cli'

      - name: Install Composer dependencies
        run: |
          cd /var/www/html
          composer install --no-dev --optimize-autoloader

      - name: Start PHP built-in server
        run: php -S sifydev.digitalrupay.com -t /var/www/html

      - name: Wait for PHP built-in server to start
        run: sleep 5

      - name: Test PHP application
        run: curl http://sifydev.digitalrupay.com/Welcome
        
