name: PHP Application Deployment

on:
  push:
    branches: [ "test" ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        run: |
          sudo yum install -y epel-release
          sudo yum install -y php php-cli php-fpm php-mysqlnd php-zip php-devel php-gd php-mcrypt php-mbstring php-curl php-xml php-pear php-bcmath php-json

      - name: Install Composer
        run: |
          sudo curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

      - name: Update PATH environment variable
        run: |
          echo 'export PATH="/usr/local/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Check if composer.json exists
        run: |
          if [ ! -f "/var/www/html/composer.json" ]; then
            cd /var/www/html
            composer init --name "your-vendor/your-project" --require-dev ""
          fi

      - name: Install Composer dependencies
        run: |
          cd /var/www/html
          /usr/local/bin/composer install --no-dev --optimize-autoloader

      - name: Start PHP built-in server
        run: php -S sifydev.digitalrupay.com -t /var/www/html &

      - name: Wait for PHP built-in server to start
        run: sleep 5

      - name: Test PHP application
        run: curl http://sifydev.digitalrupay.com/Welcome
